# Generated by Django 4.2.13 on 2024-06-06 20:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Локация')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cafes_owners', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Кафе',
                'verbose_name_plural': 'Кафе',
                'ordering': ('name',),
            },
        ),
    ]
