# Generated by Django 4.2.13 on 2024-06-06 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название отдела')),
                ('cafe', models.ManyToManyField(to='cafes.cafe', verbose_name='Кафе')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departments_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ('name',),
            },
        ),
    ]
