# Generated by Django 4.2.13 on 2024-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_product_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycookingtime',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время приготовления'),
        ),
    ]
