# Generated by Django 4.2.13 on 2024-06-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_categorycookingtime_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
    ]
