# Generated by Django 4.2.13 on 2024-06-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cooking_time',
        ),
    ]
