# Generated by Django 4.2.13 on 2024-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0007_alter_category_name_alter_orderstatus_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AlterField(
            model_name='categorycookingtime',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время приготовления(мин)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cafe',
            field=models.ManyToManyField(blank=True, null=True, to='cafes.cafe', verbose_name='Кафе'),
        ),
    ]
