# Generated by Django 4.2.13 on 2024-06-12 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0009_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CREATED_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='cafes_employees', through='cafes.Employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated_at'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
