# Generated by Django 4.2.13 on 2024-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0010_cafe_created_at_cafe_created_by_cafe_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='cafe',
            field=models.ManyToManyField(related_name='departments', to='cafes.cafe', verbose_name='Кафе'),
        ),
    ]
