# Generated by Django 4.2.13 on 2024-06-12 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0011_alter_department_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='cafes_employees', through='cafes.Employee', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
