# Generated by Django 4.2.13 on 2024-06-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0012_alter_cafe_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cafe',
            field=models.ManyToManyField(blank=True, to='cafes.cafe', verbose_name='Кафе'),
        ),
    ]
