# Generated by Django 4.2.13 on 2024-06-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0013_alter_product_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CREATED_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated_at'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterUniqueTogether(
            name='cafe',
            unique_together={('name', 'location')},
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Data joined')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_info', to='cafes.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник отдела',
                'verbose_name_plural': 'Сотрудники отделов',
                'ordering': ('-date_joined',),
                'unique_together': {('department', 'user')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='departments_members', through='cafes.Member', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники отдела'),
        ),
    ]
