# Generated by Django 4.2.13 on 2024-06-12 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0017_alter_department_options_remove_department_cafe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafedepartment',
            name='members',
        ),
        migrations.AddField(
            model_name='cafedepartment',
            name='members',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments_members', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники отдела'),
            preserve_default=False,
        ),
    ]
