# Generated by Django 4.2.13 on 2024-06-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0018_remove_cafedepartment_members_cafedepartment_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
