# Generated by Django 4.2.13 on 2024-06-12 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0020_alter_cafedepartment_options_cafe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cafedepartment',
            unique_together={('department', 'manager', 'members')},
        ),
    ]
