# Generated by Django 4.2.13 on 2024-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0021_alter_cafedepartment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='departments',
            field=models.ManyToManyField(blank=True, through='cafes.CafeDepartment', to='cafes.department', verbose_name='Отделы'),
        ),
    ]
