# Generated by Django 4.2.13 on 2024-06-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0022_alter_cafe_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafedepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_departments', to='cafes.department', verbose_name='Название отдела'),
        ),
    ]
