# Generated by Django 4.2.13 on 2024-06-15 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0023_alter_cafedepartment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafedepartment',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='departments_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='cafedepartment',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_members', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники отдела'),
        ),
    ]
