# Generated by Django 4.2.13 on 2024-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0024_alter_cafedepartment_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cooking_time',
            field=models.IntegerField(default=1, verbose_name='Время приготовления(мин)'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryCookingTime',
        ),
    ]
