# Generated by Django 4.2.13 on 2024-06-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0026_alter_position_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='address',
            field=models.CharField(default=1, max_length=256, verbose_name='Адрес кафе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafes.cafe', verbose_name='Кафе для заказа'),
        ),
    ]
