# Generated by Django 4.2.13 on 2024-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0027_cafe_address_order_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order_products', through='cafes.OrderProduct', to='cafes.product'),
        ),
    ]
