# Generated by Django 4.2.13 on 2024-06-20 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0028_order_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cafedepartment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cafedepartment',
            name='members',
        ),
        migrations.AddField(
            model_name='cafedepartment',
            name='members',
            field=models.ManyToManyField(related_name='departments_members', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники отдела'),
        ),
    ]
