# Generated by Django 4.2.13 on 2024-06-20 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0029_alter_cafedepartment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cafedepartment',
            unique_together={('department', 'manager')},
        ),
    ]
