# Generated by Django 4.2.13 on 2024-06-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0033_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nearest_cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafes.cafe', verbose_name='Ближайшее кафе'),
        ),
    ]
