# Generated by Django 4.2.13 on 2024-06-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0034_order_nearest_cafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
